version: '3.8'
services:
  db:
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=daulet
      - POSTGRES_DB=ukassa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5459:5459"
    networks:
      - default
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -q -U postgres -d ukassav2"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  db-test:
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=test
      - POSTGRES_DB=ukassa_test
    ports:
      - 5469:5469
    networks:
      - default

  ofd-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "ofd-service:latest"
    container_name: "ofd-service"
    depends_on:
      - "db"
    environment:
      - DATABASE_URL=postgresql://daulet:qwerty@db:5458/ukassa
      - DATABASE_TEST_URL=postgresql://test:qwerty@db:5468/ukassa_test
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    expose:
      - "8014"
    volumes:
      - ".:/code"
    ports:
      - "8014:8014"
    networks:
      - default
      - ukassa
    command: sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8014"

volumes:
  pgdata:

networks:
  default:
    driver: bridge
  ukassa:
    driver: bridge
    name: ukassa
